spring:
  application:
    name: "Accounts Microservices"


build:
  version: 1.0
accounts:
  messages: "Welcome  to Janie Chan Accountts QA environment web application"
  contact-details:
    customer-name: "JAN CUSTOMER name nè ăn lắm dã man"
    customer-address: "Janie chan QA address"
  on-call-supports:
    - 082332001
    - 1232
