spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''
    url: jdbc:h2:mem:microdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8082

build:
  version: 3.2
cards:
  messages: "Welcome  to Janie Chan Cards QA environment web experience application - Hoookes Tesst 12"
  contact-details:
    customer-name: "JAN CUSTOMER name nè ăn lắm dã man"
    customer-address: "Janie chan QA address"
  on-call-supports:
    - 082332001
    - 1232
