spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''
    url: jdbc:h2:mem:microdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
build:
  version: 3.0
cards:
  messages: "Welcome  to Janie Chan Cards  web application"
  contact-details:
    customer-name: "JAN CUS"
    customer-address: "Janie chan address"
  on-call-supports:
    - 082332001
    - 1232
