spring:
  application:
    name: "Loan Microservices"
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''
    url: jdbc:h2:mem:microdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: prod

server:
  port: 8082

build:
  version: 1.0
loan:
  messages: "Welcome  to Janie Chan Loan product application"
  contact-details:
    customer-name: "JAN CUS"
    customer-address: "Janie chan address"
  on-call-supports:
    - 082332001
    - 1232
