spring:
  application:
    name: "Loan Microservices"
server:
  port: 8082

build:
  version: 1.0
loan:
  messages: "Welcome  to Janie Chan Loan QA environment web application"
  contact-details:
    customer-name: "JAN CUSTOMER name nè ăn lắm dã man"
    customer-address: "Janie chan QA address"
  on-call-supports:
    - 082332001
    - 1232
